import Database from "better-sqlite3";
import fs from "fs";
import path from "path";
const dataDir=process.env.LRS_DATA_DIR||path.join(process.cwd(),"data");fs.mkdirSync(dataDir,{recursive:true});const dbPath=path.join(dataDir,"lrs-motors.db");const db=new Database(dbPath);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");
db.exec(`
CREATE TABLE IF NOT EXISTS vehicles (id TEXT PRIMARY KEY,registration_number TEXT UNIQUE,make TEXT NOT NULL,model TEXT NOT NULL,variant TEXT,year INTEGER,fuel TEXT,transmission TEXT,kilometers INTEGER DEFAULT 0,purchase_price INTEGER DEFAULT 0,selling_price INTEGER DEFAULT 0,status TEXT NOT NULL DEFAULT 'available',owner_name TEXT,owner_phone TEXT,father_name TEXT,address TEXT,registration_date TEXT,registration_validity TEXT,engine_number TEXT,chassis_number TEXT,vehicle_class TEXT,color TEXT,body_type TEXT,seating_capacity INTEGER,unladen_weight INTEGER,cubic_capacity REAL,wheelbase INTEGER,manufacturing_month_year TEXT,emission_norms TEXT,financier TEXT,registration_authority TEXT,pucc_valid_until TEXT,insurance_valid_until TEXT,remarks TEXT,workflow_status TEXT NOT NULL DEFAULT 'draft',submitted_by TEXT,reviewed_by TEXT,submitted_at TEXT,reviewed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reservations (id TEXT PRIMARY KEY,vehicle_id TEXT NOT NULL,customer_id TEXT NOT NULL,selling_price INTEGER NOT NULL,booking_amount INTEGER NOT NULL DEFAULT 0,balance_amount INTEGER NOT NULL DEFAULT 0,booking_date TEXT NOT NULL,balance_due_date TEXT,payment_method TEXT,payment_reference TEXT,notes TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY,reservation_id TEXT NOT NULL,amount INTEGER NOT NULL,payment_date TEXT NOT NULL,payment_method TEXT,payment_reference TEXT,notes TEXT,created_at TEXT NOT NULL,FOREIGN KEY(reservation_id) REFERENCES reservations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY,vehicle_id TEXT,document_type TEXT NOT NULL,file_name TEXT NOT NULL,file_path TEXT NOT NULL,review_status TEXT NOT NULL DEFAULT 'pending',review_note TEXT,uploaded_at TEXT NOT NULL,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS vehicle_photos (id TEXT PRIMARY KEY,vehicle_id TEXT NOT NULL,photo_type TEXT NOT NULL,file_path TEXT NOT NULL,optimized_path TEXT,thumbnail_path TEXT,tyre_remaining_percent INTEGER,review_status TEXT NOT NULL DEFAULT 'pending',retake_reason TEXT,captured_by TEXT,captured_at TEXT NOT NULL,reviewed_by TEXT,reviewed_at TEXT,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY,vehicle_id TEXT,actor TEXT,actor_role TEXT,action TEXT NOT NULL,field_name TEXT,old_value TEXT,new_value TEXT,note TEXT,created_at TEXT NOT NULL,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL);
`);
function addColumn(table:string,column:string,definition:string){const cols=db.prepare(`PRAGMA table_info(${table})`).all() as {name:string}[];if(!cols.some(c=>c.name===column))db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`)}
const vehicleColumns:Record<string,string>={remarks:"TEXT",workflow_status:"TEXT NOT NULL DEFAULT 'draft'",submitted_by:"TEXT",reviewed_by:"TEXT",submitted_at:"TEXT",reviewed_at:"TEXT",owner_phone:"TEXT",father_name:"TEXT",address:"TEXT",registration_validity:"TEXT",vehicle_class:"TEXT",color:"TEXT",body_type:"TEXT",seating_capacity:"INTEGER",unladen_weight:"INTEGER",cubic_capacity:"REAL",wheelbase:"INTEGER",manufacturing_month_year:"TEXT",emission_norms:"TEXT",financier:"TEXT",registration_authority:"TEXT",pucc_valid_until:"TEXT",insurance_valid_until:"TEXT"};for(const[column,definition]of Object.entries(vehicleColumns))addColumn("vehicles",column,definition);addColumn("documents","review_status","TEXT NOT NULL DEFAULT 'pending'");addColumn("documents","review_note","TEXT");
db.exec(`CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status);CREATE INDEX IF NOT EXISTS idx_vehicles_workflow ON vehicles(workflow_status);CREATE INDEX IF NOT EXISTS idx_reservations_vehicle ON reservations(vehicle_id);CREATE INDEX IF NOT EXISTS idx_reservations_due ON reservations(balance_due_date);CREATE INDEX IF NOT EXISTS idx_photos_vehicle ON vehicle_photos(vehicle_id);CREATE INDEX IF NOT EXISTS idx_photos_review ON vehicle_photos(review_status);`);
export {db,dbPath,dataDir};
