import Database from "better-sqlite3";
import fs from "fs";
import path from "path";
const dataDir=process.env.LRS_DATA_DIR||path.join(process.cwd(),"data");fs.mkdirSync(dataDir,{recursive:true});const dbPath=path.join(dataDir,"lrs-motors.db");const db=new Database(dbPath);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");
db.exec(`
CREATE TABLE IF NOT EXISTS vehicles (id TEXT PRIMARY KEY,registration_number TEXT UNIQUE,make TEXT NOT NULL,model TEXT NOT NULL,variant TEXT,year INTEGER,fuel TEXT,transmission TEXT,kilometers INTEGER DEFAULT 0,purchase_price INTEGER DEFAULT 0,selling_price INTEGER DEFAULT 0,status TEXT NOT NULL DEFAULT 'available',owner_name TEXT,owner_phone TEXT,father_name TEXT,address TEXT,registration_date TEXT,registration_validity TEXT,engine_number TEXT,chassis_number TEXT,vehicle_class TEXT,color TEXT,body_type TEXT,seating_capacity INTEGER,unladen_weight INTEGER,cubic_capacity REAL,wheelbase INTEGER,manufacturing_month_year TEXT,emission_norms TEXT,financier TEXT,registration_authority TEXT,pucc_valid_until TEXT,insurance_valid_until TEXT,remarks TEXT,workflow_status TEXT NOT NULL DEFAULT 'draft',submitted_by TEXT,reviewed_by TEXT,submitted_at TEXT,reviewed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS staff_accounts (id TEXT PRIMARY KEY,first_name TEXT NOT NULL,middle_name TEXT,last_name TEXT NOT NULL,mobile TEXT NOT NULL UNIQUE,email TEXT NOT NULL UNIQUE,address TEXT,aadhaar_number TEXT,pan_number TEXT,aadhaar_file TEXT,pan_file TEXT,profile_photo TEXT,requested_role TEXT,assigned_role TEXT,approval_status TEXT NOT NULL DEFAULT 'pending',password_hash TEXT NOT NULL,created_at TEXT NOT NULL,approved_at TEXT,approved_by TEXT);
CREATE TABLE IF NOT EXISTS hr_employees (id TEXT PRIMARY KEY,staff_id TEXT NOT NULL UNIQUE,employee_code TEXT,department TEXT,designation TEXT,salary INTEGER NOT NULL DEFAULT 0,date_joined TEXT,employment_status TEXT NOT NULL DEFAULT 'pending',notes TEXT,updated_at TEXT NOT NULL,FOREIGN KEY(staff_id) REFERENCES staff_accounts(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS reservations (id TEXT PRIMARY KEY,vehicle_id TEXT NOT NULL,customer_id TEXT NOT NULL,selling_price INTEGER NOT NULL,booking_amount INTEGER NOT NULL DEFAULT 0,balance_amount INTEGER NOT NULL DEFAULT 0,booking_date TEXT NOT NULL,balance_due_date TEXT,payment_method TEXT,payment_reference TEXT,notes TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY,reservation_id TEXT NOT NULL,amount INTEGER NOT NULL,payment_date TEXT NOT NULL,payment_method TEXT,payment_reference TEXT,notes TEXT,created_at TEXT NOT NULL,FOREIGN KEY(reservation_id) REFERENCES reservations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY,vehicle_id TEXT,document_type TEXT NOT NULL,file_name TEXT NOT NULL,file_path TEXT NOT NULL,review_status TEXT NOT NULL DEFAULT 'pending',review_note TEXT,uploaded_at TEXT NOT NULL,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS vehicle_photos (id TEXT PRIMARY KEY,vehicle_id TEXT NOT NULL,photo_type TEXT NOT NULL,file_path TEXT NOT NULL,optimized_path TEXT,thumbnail_path TEXT,tyre_remaining_percent INTEGER,review_status TEXT NOT NULL DEFAULT 'pending',retake_reason TEXT,captured_by TEXT,captured_at TEXT NOT NULL,reviewed_by TEXT,reviewed_at TEXT,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY,vehicle_id TEXT,actor TEXT,actor_role TEXT,action TEXT NOT NULL,field_name TEXT,old_value TEXT,new_value TEXT,note TEXT,created_at TEXT NOT NULL,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS follow_ups (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,follow_up_no INTEGER NOT NULL,scheduled_at TEXT,completed_at TEXT,channel TEXT DEFAULT 'call',note TEXT,outcome TEXT,created_by TEXT,created_at TEXT NOT NULL,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS customer_communications (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,channel TEXT NOT NULL,direction TEXT NOT NULL DEFAULT 'outbound',message_type TEXT,status TEXT NOT NULL DEFAULT 'draft',message TEXT,external_id TEXT,created_by TEXT,created_at TEXT NOT NULL,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY,value TEXT,updated_by TEXT,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS message_queue (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,channel TEXT NOT NULL,message_type TEXT NOT NULL,message TEXT NOT NULL,scheduled_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,external_id TEXT,created_by TEXT,created_at TEXT NOT NULL,sent_at TEXT,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE);
`);
function columnNames(table:string){return new Set((db.prepare(`PRAGMA table_info(${table})`).all() as {name:string}[]).map(c=>c.name.toLowerCase()))}
function addMissingColumns(table:string,definitions:Record<string,string>){const existing=columnNames(table);for(const[column,definition]of Object.entries(definitions)){const key=column.toLowerCase();if(existing.has(key))continue;try{db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);existing.add(key)}catch(e){const message=e instanceof Error?e.message:String(e);if(!/duplicate column name/i.test(message))throw e;existing.add(key)}}}
addMissingColumns("vehicles",{remarks:"TEXT",workflow_status:"TEXT NOT NULL DEFAULT 'draft'",submitted_by:"TEXT",reviewed_by:"TEXT",submitted_at:"TEXT",reviewed_at:"TEXT",owner_phone:"TEXT",father_name:"TEXT",address:"TEXT",registration_validity:"TEXT",vehicle_class:"TEXT",color:"TEXT",body_type:"TEXT",seating_capacity:"INTEGER",unladen_weight:"INTEGER",cubic_capacity:"REAL",wheelbase:"INTEGER",manufacturing_month_year:"TEXT",emission_norms:"TEXT",financier:"TEXT",registration_authority:"TEXT",pucc_valid_until:"TEXT",insurance_valid_until:"TEXT"});
addMissingColumns("customers",{lead_status:"TEXT NOT NULL DEFAULT 'new'",lead_source:"TEXT NOT NULL DEFAULT 'walk-in'",vehicle_type:"TEXT",interested_make:"TEXT",interested_model:"TEXT",interested_vehicle_id:"TEXT",budget:"INTEGER",price_discussed:"INTEGER",assigned_staff:"TEXT",next_follow_up:"TEXT",test_drive_at:"TEXT",follow_up_count:"INTEGER NOT NULL DEFAULT 0",marketing_consent:"INTEGER NOT NULL DEFAULT 0",purchased:"INTEGER NOT NULL DEFAULT 0",purchased_vehicle_id:"TEXT",purchase_date:"TEXT",remarks:"TEXT"});
addMissingColumns("documents",{review_status:"TEXT NOT NULL DEFAULT 'pending'",review_note:"TEXT"});
db.exec(`CREATE INDEX IF NOT EXISTS idx_staff_approval ON staff_accounts(approval_status);CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status);CREATE INDEX IF NOT EXISTS idx_vehicles_workflow ON vehicles(workflow_status);CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);CREATE INDEX IF NOT EXISTS idx_customers_status ON customers(lead_status);CREATE INDEX IF NOT EXISTS idx_customers_followup ON customers(next_follow_up);CREATE INDEX IF NOT EXISTS idx_message_queue_due ON message_queue(status,scheduled_at);`);
export {db,dbPath,dataDir};