package com.lrsmotors.app
import android.Manifest
import android.app.*
import android.content.*
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat

class MainActivity:ComponentActivity(){private val permissions=registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){};override fun onCreate(b:Bundle?){super.onCreate(b);permissions.launch(arrayOf(Manifest.permission.READ_PHONE_STATE,Manifest.permission.READ_CALL_LOG,Manifest.permission.CALL_PHONE,Manifest.permission.POST_NOTIFICATIONS));val p=intent.getStringExtra("action_phone")?:intent.getStringExtra("after_call_phone");setContent{LeadApp(this,p,intent.hasExtra("action_phone"))}}}
@Composable fun LeadApp(c:Context,p0:String?,action:Boolean){val s=remember{LeadStore(c)};var page by remember{mutableStateOf(if(action)"action" else if(p0.isNullOrBlank())"home" else "edit")};var p by remember{mutableStateOf(p0.orEmpty())};var r by remember{mutableIntStateOf(0)};MaterialTheme{Scaffold(bottomBar={NavigationBar{NavigationBarItem(page=="home",{page="home"},{},{Text("Dashboard")});NavigationBarItem(page=="leads",{page="leads"},{},{Text("Leads")})}}){x->Box(Modifier.padding(x)){when(page){"leads"->Leads(s,r){p=it;page="edit"};"edit"->Editor(c,s,p){r++;page="leads"};"action"->ActionScreen(c,s,p){r++;page="leads"};else->Dashboard(s,r,{p=it;page="edit"},{page="leads"})}}}}}
@Composable fun Dashboard(s:LeadStore,r:Int,open:(String)->Unit,leads:()->Unit){val a=remember(r){s.all()};LazyColumn(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("LRS Motors",style=MaterialTheme.typography.headlineMedium);Text("Call Lead Manager")};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("Leads",a.size.toString(),Modifier.weight(1f));Metric("Hot",a.count{it.status=="Hot"}.toString(),Modifier.weight(1f));Metric("24h",a.count{it.actionState=="WAITING"}.toString(),Modifier.weight(1f))}};item{Button(leads,Modifier.fillMaxWidth()){Text("View All Leads")};Text("Recent callers",style=MaterialTheme.typography.titleLarge)};items(a.take(10)){Card(Modifier.fillMaxWidth().clickable{open(it.phone)}){Column(Modifier.padding(14.dp)){Text(if(it.name.isBlank())it.phone else it.name);Text("${it.phone} · ${it.type} · ${it.vehicle}")}}}}}
@Composable fun Metric(t:String,v:String,m:Modifier){Card(m){Column(Modifier.padding(12.dp)){Text(v,style=MaterialTheme.typography.headlineSmall);Text(t)}}}
@Composable fun Leads(s:LeadStore,r:Int,open:(String)->Unit){var q by remember{mutableStateOf("")};var z by remember{mutableIntStateOf(0)};val a=remember(q,r,z){s.all(q)};Column(Modifier.fillMaxSize().padding(18.dp)){Text("Leads",style=MaterialTheme.typography.headlineMedium);OutlinedTextField(q,{q=it},label={Text("Search number, name or vehicle")},modifier=Modifier.fillMaxWidth());LazyColumn{items(a,key={it.id}){l->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Column(Modifier.clickable{open(l.phone)}){Text(if(l.name.isBlank())l.phone else l.name);Text("${l.phone} · ${l.type} · ${l.vehicle} · ${l.status}")};TextButton({s.delete(l.phone);z++}){Text("Delete Lead")}}}}}}}
@Composable fun Editor(c:Context,s:LeadStore,seed:String,done:()->Unit){val p=LeadStore.normalize(seed);val o=remember(p){s.find(p)};var n by remember{mutableStateOf(o?.name.orEmpty())};var t by remember{mutableStateOf(o?.type?:"Car")};var v by remember{mutableStateOf(o?.vehicle.orEmpty())};var b by remember{mutableStateOf(o?.budget.orEmpty())};var st by remember{mutableStateOf(o?.status?:"New")};var note by remember{mutableStateOf(o?.notes.orEmpty())};LazyColumn(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Caller: $p",style=MaterialTheme.typography.headlineSmall);Text("Number captured automatically")};item{F("Customer name (optional)",n){n=it}};item{Row{FilterChip(t=="Car",{t="Car"},{Text("Car")});Spacer(Modifier.width(8.dp));FilterChip(t=="Bike",{t="Bike"},{Text("Bike")})}};item{F("Which car / bike?",v){v=it}};item{F("Budget (optional)",b){b=it}};item{F("Notes (optional)",note){note=it}};item{Row{listOf("New","Hot","Warm","Purchased","Lost").forEach{FilterChip(st==it,{st=it},{Text(it)})}}};item{Button({val due=System.currentTimeMillis()+86400000L;s.save(p,n,t,v,b,st,note,due);schedule24(c,p,v,due);done()},enabled=p.isNotBlank()&&v.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text("Save Lead")}}}}
@Composable fun ActionScreen(c:Context,s:LeadStore,p:String,done:()->Unit){val l=remember(p){s.find(p)};var wa by remember{mutableStateOf(l?.actionState=="WHATSAPP")};Column(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("24 Hour Follow-up",style=MaterialTheme.typography.headlineMedium);Text(l?.name?.ifBlank{p}?:p);Text(l?.vehicle.orEmpty());if(!wa){Button({whatsapp(c,p,l?.name.orEmpty(),l?.vehicle.orEmpty());s.setAction(p,"WHATSAPP");wa=true},Modifier.fillMaxWidth()){Text("WhatsApp")};Button({startCall(c,p);s.setAction(p,"CALLING");c.getSharedPreferences("call_state",Context.MODE_PRIVATE).edit().putString("pending_followup_call",p).apply()},Modifier.fillMaxWidth()){Text("Call")}}else{Text("WhatsApp selected. Call the customer when ready.");Button({startCall(c,p);s.setAction(p,"CALLING");c.getSharedPreferences("call_state",Context.MODE_PRIVATE).edit().putString("pending_followup_call",p).apply()},Modifier.fillMaxWidth()){Text("Call")}};Text("After the follow-up call ends, this pending action is automatically completed and disappears.")}}
@Composable fun F(l:String,v:String,set:(String)->Unit){OutlinedTextField(v,set,label={Text(l)},modifier=Modifier.fillMaxWidth(),singleLine=true)}
fun schedule24(c:Context,p:String,v:String,at:Long){val am=c.getSystemService(Context.ALARM_SERVICE) as AlarmManager;val pi=PendingIntent.getBroadcast(c,p.hashCode(),Intent(c,ReminderReceiver::class.java).putExtra("phone",p).putExtra("vehicle",v),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi)}
fun whatsapp(c:Context,p:String,n:String,v:String){val text="Hello ${n.ifBlank{"Sir/Madam"}}, this is LRS Motors regarding ${v.ifBlank{"your vehicle enquiry"}}. Would you like to book a test drive?";c.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/91${LeadStore.normalize(p)}?text=${Uri.encode(text)}")))}
fun startCall(c:Context,p:String){val u=Uri.parse("tel:$p");if(ContextCompat.checkSelfPermission(c,Manifest.permission.CALL_PHONE)==PackageManager.PERMISSION_GRANTED)c.startActivity(Intent(Intent.ACTION_CALL,u))else c.startActivity(Intent(Intent.ACTION_DIAL,u))}