"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { LayoutDashboard, Car, Users, BadgeIndianRupee, FileText, BarChart3, Settings, Menu, X, Crown } from "lucide-react";
import { useState } from "react";
import { useAuth } from "@/providers/AuthProvider";
const navItems=[{href:"/dashboard",label:"Dashboard",icon:LayoutDashboard},{href:"/inventory",label:"Inventory",icon:Car},{href:"/customers",label:"Customers",icon:Users},{href:"/sales",label:"Sales",icon:BadgeIndianRupee},{href:"/documents",label:"Documents",icon:FileText},{href:"/reports",label:"Reports",icon:BarChart3},{href:"/settings",label:"Settings",icon:Settings}];
export function Navigation(){const pathname=usePathname();const{user}=useAuth();const[open,setOpen]=useState(false);const links=<>{navItems.map(({href,label,icon:Icon})=>{const active=pathname===href;return <Link key={href} href={href} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium transition-all ${active?"border border-amber-400/40 bg-gradient-to-r from-amber-400/20 to-transparent text-amber-300 shadow-[inset_3px_0_0_#f5c451]":"text-zinc-400 hover:bg-white/5 hover:text-white"}`}><Icon className="h-5 w-5"/><span>{label}</span></Link>})}</>;
return <><div className="fixed left-0 right-0 top-0 z-50 flex h-16 items-center justify-between border-b border-amber-400/15 bg-[#080a0b]/95 px-4 text-white backdrop-blur md:hidden"><div><div className="text-xl font-black italic tracking-wider text-amber-300">LRS</div><div className="text-[9px] tracking-[.32em] text-amber-400">MOTORS</div></div><button onClick={()=>setOpen(!open)} className="rounded-lg border border-white/10 p-2">{open?<X/>:<Menu/>}</button></div>{open&&<nav className="fixed inset-x-0 top-16 z-40 border-b border-amber-400/15 bg-[#080a0b] p-4 md:hidden">{links}</nav>}<nav className="hidden md:fixed md:inset-y-0 md:left-0 md:z-40 md:flex md:w-64 md:flex-col md:border-r md:border-amber-400/15 md:bg-[radial-gradient(circle_at_top,#17130a_0,#090b0c_34%,#050607_100%)] md:text-white"><div className="border-b border-amber-400/15 px-7 py-7"><div className="text-3xl font-black italic tracking-wider text-amber-300">LRS</div><div className="mt-[-4px] text-xs font-bold tracking-[.42em] text-amber-400">MOTORS</div><div className="mt-2 text-[9px] tracking-[.24em] text-zinc-500">DRIVE YOUR DREAM</div></div><div className="flex-1 space-y-1 overflow-y-auto px-3 py-5">{links}</div><div className="m-4 rounded-2xl border border-amber-400/35 bg-amber-400/[.04] p-4"><div className="flex items-center gap-3"><div className="rounded-full border border-amber-400/50 p-2 text-amber-300"><Crown className="h-5 w-5"/></div><div><p className="font-semibold text-amber-200">{user?.name||"Director"}</p><p className="text-xs capitalize text-zinc-500">{user?.role||"Super Admin"}</p></div></div><div className="mt-3 flex items-center gap-2 text-xs text-zinc-400"><span className="h-2 w-2 rounded-full bg-green-500"/>PC Server Online</div></div><div className="px-5 pb-5 text-[10px] tracking-widest text-zinc-600">LRS MOTORS • PC SERVER</div></nav></>}
